"use client";
import { FormEvent, useState } from "react";
import LanguageSwitcher from "../../components/LanguageSwitcher";
import { Language, localizeAuthError, useI18n } from "../../lib/i18n";
import { supabase } from "../../lib/supabase";

const copy: Record<Language, Record<string, string>> = {
  de: { title: "Konto erstellen", intro: "Starte mit deinen persönlichen Schiessresultaten.", email: "E-Mail", password: "Passwort", passwordHint: "Mindestens 8 Zeichen", loading: "Konto wird erstellt...", submit: "Konto erstellen", success: "Konto wurde erstellt. Bitte prüfe deine E-Mails und bestätige deine Adresse.", error: "Fehler" },
  fr: { title: "Créer un compte", intro: "Commence à suivre tes résultats de tir personnels.", email: "E-mail", password: "Mot de passe", passwordHint: "Au moins 8 caractères", loading: "Création du compte…", submit: "Créer un compte", success: "Le compte a été créé. Consulte tes e-mails et confirme ton adresse.", error: "Erreur" },
  it: { title: "Crea un account", intro: "Inizia a registrare i tuoi risultati di tiro personali.", email: "E-mail", password: "Password", passwordHint: "Almeno 8 caratteri", loading: "Creazione dell’account…", submit: "Crea account", success: "L’account è stato creato. Controlla le e-mail e conferma il tuo indirizzo.", error: "Errore" },
  en: { title: "Create an account", intro: "Start tracking your personal shooting results.", email: "Email", password: "Password", passwordHint: "At least 8 characters", loading: "Creating account…", submit: "Create account", success: "Your account has been created. Check your email and confirm your address.", error: "Error" },
};

export default function RegisterPage() {
  const { language } = useI18n(); const text = copy[language];
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(false);
  async function handleSubmit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); setMessage(""); const { error } = await supabase.auth.signUp({ email, password, options: { data: { language } } }); if (error) { setMessage(`${text.error}: ${localizeAuthError(error.message, language)}`); setLoading(false); return; } setMessage(text.success); setLoading(false); }
  return <main data-i18n-explicit className="min-h-screen bg-slate-50 px-6 py-10"><div className="mx-auto max-w-md"><div className="flex justify-end"><LanguageSwitcher compact /></div><div className="flex items-center justify-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-full bg-red-600 text-xl text-white">◎</div><p className="text-xl font-bold text-slate-900">EasyShooter</p></div><div className="mt-8 text-center"><h1 className="text-3xl font-bold text-slate-900">{text.title}</h1><p className="mt-2 text-slate-600">{text.intro}</p></div>
    <form onSubmit={handleSubmit} className="mt-8 rounded-2xl border bg-white p-6 shadow-sm"><div className="mb-5"><label htmlFor="email" className="mb-2 block text-sm font-medium text-slate-700">{text.email}</label><input id="email" type="email" autoComplete="email" required value={email} onChange={(event) => setEmail(event.target.value)} className="w-full rounded-lg border border-slate-300 px-4 py-3 text-slate-900 outline-none focus:border-red-500" placeholder="name@example.ch" /></div><div className="mb-6"><label htmlFor="password" className="mb-2 block text-sm font-medium text-slate-700">{text.password}</label><input id="password" type="password" autoComplete="new-password" required minLength={8} value={password} onChange={(event) => setPassword(event.target.value)} className="w-full rounded-lg border border-slate-300 px-4 py-3 text-slate-900 outline-none focus:border-red-500" placeholder={text.passwordHint} /></div><button type="submit" disabled={loading} className="w-full rounded-lg bg-red-600 px-5 py-3 font-semibold text-white disabled:opacity-50">{loading ? text.loading : text.submit}</button>{message && <div className="mt-5 rounded-lg bg-slate-100 p-4 text-sm text-slate-700">{message}</div>}</form></div></main>;
}
